### ISSUE TITLE
Simplified boost handling for KaHyPar

### ISSUE THREAD

**Issue by SebastianSchlag** [nasa/hybridq#95]
Hey folks, 

I just saw the long troubleshooting list regarding the KaHyPar installation. Sorry about the troubles boost causes.

One approach that might simplify things is to use the `-DKAHYPAR_USE_MINIMAL_BOOST=ON` cmake flag. This will automatically download a correct boost version and extract and build the required components.

**Comment by s-mandra** [comment]
Thanks for the tip! I'll update the `README.md` to include your flag as well.

**Comment by s-mandra** [comment]
See [https://github.com/kahypar/kahypar/issues/101](https://github.com/kahypar/kahypar/issues/101)
